const configured = SUPABASE_URL && !SUPABASE_URL.includes('PASTE_') && SUPABASE_ANON_KEY && !SUPABASE_ANON_KEY.includes('PASTE_');
const client = configured ? supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY) : null;
let classId=null, studentName='', studentSession=null;
const show=x=>{['setup','login','teacher','join','student'].forEach(i=>document.getElementById(i).classList.add('hidden'));document.getElementById(x).classList.remove('hidden')};
if(!configured) show('setup');
async function login(){
 if(!client)return;
 const email=v('email'),password=v('pw'); if(!email||!password)return msg('loginMsg','Enter your email and password.');
 const {error}=await client.auth.signInWithPassword({email,password}); if(error)return msg('loginMsg',error.message);
 show('teacher'); await tab('classes');
}
async function logout(){await client.auth.signOut();show('login')}
function studentJoin(){show('join')}
async function tab(t){show('teacher');let c=document.getElementById('content');c.innerHTML='<div class="panel"><p>Loading…</p></div>';try{if(t==='classes')c.innerHTML=await classes();if(t==='reading')c.innerHTML=await reading();if(t==='vocab')c.innerHTML=await vocab();if(t==='grammar')c.innerHTML=await grammar();if(t==='tests')c.innerHTML=await tests();if(t==='results')c.innerHTML=await results()}catch(e){c.innerHTML=`<div class="panel"><p class="error">${E(e.message)}</p></div>`}}
async function classes(){const {data,error}=await client.from('classes').select('*').order('id');if(error)throw error;return `<div class=panel><h2>Classes</h2><div class=grid>${(data||[]).map(c=>`<div class=stat><h3>${E(c.name)}</h3><p>${E(c.level)} · Room code <b>${E(c.code)}</b></p><button onclick="classId=${c.id};tab('reading')">Open class</button></div>`).join('')||'<p>No classes yet.</p>'}</div></div><div class=panel><h3>Create a class</h3><input id=cn placeholder="Class name"><select id=cl><option>B1</option><option>B2</option><option>C1</option><option>C2</option></select><input id=cc placeholder="Room code"><button onclick="addClass()">Create</button></div>`}
async function addClass(){const n=v('cn'),l=v('cl'),c=v('cc').toUpperCase();if(!n||!c)return alert('Enter class name and room code.');const {error}=await client.from('classes').insert({name:n,level:l,code:c});if(error)return alert(error.message);tab('classes')}
async function reading(){const {data:cs,error:e}=await client.from('classes').select('*').order('id');if(e)throw e;let q=client.from('readings').select('*').order('date',{ascending:false});if(classId)q=q.eq('class_id',classId);const {data:rs,error}=await q;if(error)throw error;return `<div class=panel><h2>Reading Lab</h2><p>Add texts periodically. New language items can be transferred to Vocabulary.</p>${(cs||[]).filter(c=>!classId||c.id===classId).map(c=>`<h3>${E(c.name)}</h3>${(rs||[]).filter(r=>r.class_id===c.id).map(r=>`<div class=item><b>${E(r.title)}</b> · ${E(r.level)} · ${E(r.date)}<br><button onclick="openReading(${r.id})">Open</button></div>`).join('')||'<p>No texts yet.</p>'}`).join('')}</div><div class=panel><h3>Add text</h3><select id=rc>${(cs||[]).map(c=>`<option value=${c.id}>${E(c.name)}</option>`).join('')}</select><input id=rt placeholder="Title"><input id=rl placeholder="Level (B2/C1)"><input id=rd type=date><textarea id=rx placeholder="Paste the text here"></textarea><textarea id=ri placeholder="One item per line: word | Polish meaning | part of speech"></textarea><button onclick="addReading()">Add to Reading Lab</button></div>`}
async function addReading(){const items=v('ri').split('\n').filter(Boolean).map(x=>x.split('|').map(s=>s.trim()));const {error}=await client.from('readings').insert({class_id:+v('rc'),title:v('rt'),level:v('rl'),date:v('rd')||new Date().toISOString().slice(0,10),text:v('rx'),items});if(error)return alert(error.message);tab('reading')}
async function openReading(id){const {data:r,error}=await client.from('readings').select('*').eq('id',id).single();if(error)return alert(error.message);document.getElementById('content').innerHTML=`<div class=panel><button class=secondary onclick="tab('reading')">← Back</button><h2>${E(r.title)}</h2><div class=reading>${E(r.text)}</div><h3>New language items</h3>${(r.items||[]).map((p,i)=>`<div class=item><b>${E(p[0])}</b> — ${E(p[1]||'')} <span class=tag>${E(p[2]||'')}</span><button onclick="toVocab(${r.id},${i})">Add to Vocabulary</button></div>`).join('')}</div>`}
async function toVocab(rid,i){const {data:r,error:e}=await client.from('readings').select('*').eq('id',rid).single();if(e) return alert(e.message);const p=r.items[i]||[];const {error}=await client.from('vocabulary').insert({class_id:r.class_id,word:p[0]||'',meaning:p[1]||'',pos:p[2]||'',level:r.level,example:'',topic:'From Reading Lab'});if(error)return alert(error.message);alert('Added to Vocabulary.')}
async function vocab(){const {data:cs,error:e}=await client.from('classes').select('*').order('id');if(e)throw e;const {data:vs,error}=await client.from('vocabulary').select('*').order('id',{ascending:false});if(error)throw error;return `<div class=panel><h2>Vocabulary</h2>${(cs||[]).map(c=>`<h3>${E(c.name)}</h3>${(vs||[]).filter(x=>x.class_id===c.id).map(x=>`<div class=item><b>${E(x.word)}</b> — ${E(x.meaning)} <span class=tag>${E(x.level)}</span><span class=tag>${E(x.pos||'')}</span><p>${E(x.example||'')}</p></div>`).join('')||'<p>No vocabulary yet.</p>'}`).join('')}</div>`}
async function grammar(){const {data:cs,error:e}=await client.from('classes').select('*').order('id');if(e)throw e;const {data:gs,error}=await client.from('grammar').select('*').order('id',{ascending:false});if(error)throw error;return `<div class=panel><h2>Grammar</h2>${(gs||[]).map(g=>`<div class=item><b>${E(g.area)}</b> <span class=tag>${E(g.level)}</span><p>${E(g.question)}</p><b>Answer:</b> ${E(g.answer)}<p>${E(g.explanation||'')}</p></div>`).join('')||'<p>No grammar questions yet.</p>'}</div><div class=panel><h3>Add grammar question</h3><select id=gc>${(cs||[]).map(c=>`<option value=${c.id}>${E(c.name)}</option>`).join('')}</select><input id=ga placeholder="Grammar area"><input id=gl placeholder="CEFR level"><textarea id=gq placeholder="Question"></textarea><input id=gw placeholder="Correct answer"><input id=go placeholder="Distractors separated by |"><textarea id=ge placeholder="Explanation"></textarea><button onclick="addGrammar()">Add</button></div>`}
async function addGrammar(){const {error}=await client.from('grammar').insert({class_id:+v('gc'),area:v('ga'),level:v('gl'),question:v('gq'),answer:v('gw'),options:v('go').split('|').filter(Boolean),explanation:v('ge')});if(error)return alert(error.message);tab('grammar')}
async function tests(){const {data:ts,error}=await client.from('tests').select('*').order('id',{ascending:false});if(error)throw error;const {data:cs,error:e}=await client.from('classes').select('*').order('id');if(e)throw e;return `<div class=panel><h2>Tests</h2>${(ts||[]).map(t=>`<div class=item><b>${E(t.title)}</b> · ${E(t.type)} · ${(t.questions||[]).length} questions</div>`).join('')||'<p>No tests yet.</p>'}</div><div class=panel><h3>Create test</h3><input id=tt placeholder="Test title"><select id=tc>${(cs||[]).map(c=>`<option value=${c.id}>${E(c.name)}</option>`).join('')}</select><select id=ty><option>vocabulary</option><option>grammar</option></select><input id=tn type=number value=5 min=1><button onclick="makeTest()">Create</button></div>`}
async function makeTest(){const cid=+v('tc'),type=v('ty');let bank;if(type==='vocabulary'){let r=await client.from('vocabulary').select('*').eq('class_id',cid);if(r.error)return alert(r.error.message);bank=r.data||[]}else{let r=await client.from('grammar').select('*').eq('class_id',cid);if(r.error)return alert(r.error.message);bank=r.data||[]}if(!bank.length)return alert('No items available.');bank=shuffle(bank).slice(0,+v('tn'));let qs=bank.map(x=>type==='vocabulary'?{p:`What is the Polish meaning of “${x.word}”?`,a:x.meaning,o:shuffle([x.meaning,...shuffle(bank.filter(y=>y.meaning!==x.meaning).map(y=>y.meaning)).slice(0,3)])}:{p:x.question,a:x.answer,o:shuffle([x.answer,...(x.options||[])])});const {error}=await client.from('tests').insert({class_id:cid,title:v('tt')||'Untitled test',type,questions:qs});if(error)return alert(error.message);tab('tests')}
async function results(){const {data:rs,error}=await client.from('results').select('*').order('created_at',{ascending:false});if(error)throw error;return `<div class=panel><h2>Results</h2>${(rs||[]).map(r=>`<div class=item><b>${E(r.student)}</b> · ${E(r.title)} · <b>${r.score}/${r.total}</b> (${Math.round(r.score/r.total*100)}%)</div>`).join('')||'<p>No results yet.</p>'}</div>`}
async function join(){const code=v('code').toUpperCase(),n=v('name');const {data:c,error}=await client.from('classes').select('*').eq('code',code).single();if(error||!c||!n)return msg('msg','Enter a valid room code and your name.');const {data:sessionData,error:authError}=await client.auth.signInAnonymously();if(authError)return msg('msg','Student sign-in is not enabled yet in Supabase.');studentSession=sessionData.session;classId=c.id;studentName=n;show('student');await studentHome()}
async function studentHome(){const {data:rs}=await client.from('readings').select('*').eq('class_id',classId).order('date',{ascending:false});const {data:ts}=await client.from('tests').select('*').eq('class_id',classId).order('id',{ascending:false});const {data:c}=await client.from('classes').select('*').eq('id',classId).single();document.getElementById('student').innerHTML=`<div class=panel><h2>Welcome, ${E(studentName)}</h2><p>Class: ${E(c.name)}</p></div><div class=panel><h2>Reading Lab</h2>${(rs||[]).map(r=>`<div class=item><b>${E(r.title)}</b><button onclick="studentRead(${r.id})">Read</button></div>`).join('')||'<p>No texts.</p>'}</div><div class=panel><h2>Tests</h2>${(ts||[]).map(t=>`<div class=item><b>${E(t.title)}</b> · ${(t.questions||[]).length} questions <button onclick="take(${t.id})">Start</button></div>`).join('')||'<p>No tests.</p>'}</div>`}
async function studentRead(id){const {data:r}=await client.from('readings').select('*').eq('id',id).single();document.getElementById('student').innerHTML=`<div class=panel><button class=secondary onclick="studentHome()">← Back</button><h2>${E(r.title)}</h2><div class=reading>${E(r.text)}</div><h3>Language items</h3>${(r.items||[]).map(p=>`<div class=item><b>${E(p[0])}</b> — ${E(p[1]||'')} <span class=tag>${E(p[2]||'')}</span></div>`).join('')}</div>`}
async function take(id){const {data:t,error}=await client.from('tests').select('*').eq('id',id).single();if(error)return alert(error.message);document.getElementById('student').innerHTML=`<div class=panel><h2>${E(t.title)}</h2>${(t.questions||[]).map((q,i)=>`<div class=item><b>${i+1}. ${E(q.p)}</b>${shuffle((q.o||[]).slice()).map(o=>`<label style="display:block;margin:8px"><input type=radio name=q${i} value="${A(o)}"> ${E(o)}</label>`).join('')}</div>`).join('')}<button onclick="submitTest(${t.id})">Submit</button></div>`}
async function submitTest(id){const {data:t,error}=await client.from('tests').select('*').eq('id',id).single();if(error)return alert(error.message);let s=0;(t.questions||[]).forEach((q,i)=>{const x=document.querySelector(`input[name=q${i}]:checked`);if(x&&x.value===q.a)s++});const {error:re}=await client.from('results').insert({class_id:classId,student:studentName,title:t.title,score:s,total:(t.questions||[]).length});if(re)return alert(re.message);document.getElementById('student').innerHTML=`<div class="panel success"><h2>Completed</h2><p>Your score: <b>${s}/${(t.questions||[]).length}</b> (${Math.round(s/(t.questions||[]).length*100)}%)</p><button onclick="studentHome()">Back</button></div>`}
function v(id){return document.getElementById(id)?.value.trim()||''}function msg(id,s){document.getElementById(id).textContent=s}function shuffle(a){return a.sort(()=>Math.random()-.5)}function E(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}function A(s){return String(s).replace(/"/g,'&quot;')}
