-- English Learning Platform — Supabase database setup
-- Run this in Supabase -> SQL Editor after creating your project.

create table if not exists public.classes (
  id bigint generated by default as identity primary key,
  name text not null,
  code text not null unique,
  level text not null,
  created_at timestamptz default now()
);
create table if not exists public.vocabulary (
  id bigint generated by default as identity primary key,
  class_id bigint not null references public.classes(id) on delete cascade,
  word text not null, meaning text not null, example text default '', level text default '', pos text default '', topic text default '', created_at timestamptz default now()
);
create table if not exists public.grammar (
  id bigint generated by default as identity primary key,
  class_id bigint not null references public.classes(id) on delete cascade,
  area text default '', level text default '', question text not null, answer text not null, options jsonb default '[]'::jsonb, explanation text default '', created_at timestamptz default now()
);
create table if not exists public.readings (
  id bigint generated by default as identity primary key,
  class_id bigint not null references public.classes(id) on delete cascade,
  title text not null, level text default '', date date default current_date, text text not null, items jsonb default '[]'::jsonb, created_at timestamptz default now()
);
create table if not exists public.tests (
  id bigint generated by default as identity primary key,
  class_id bigint not null references public.classes(id) on delete cascade,
  title text not null, type text not null, questions jsonb not null, created_at timestamptz default now()
);
create table if not exists public.results (
  id bigint generated by default as identity primary key,
  class_id bigint not null references public.classes(id) on delete cascade,
  student text not null, title text not null, score integer not null, total integer not null, created_at timestamptz default now()
);
create table if not exists public.teachers (
  user_id uuid primary key references auth.users(id) on delete cascade
);

alter table public.classes enable row level security;
alter table public.vocabulary enable row level security;
alter table public.grammar enable row level security;
alter table public.readings enable row level security;
alter table public.tests enable row level security;
alter table public.results enable row level security;
alter table public.teachers enable row level security;

create or replace function public.is_teacher() returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.teachers where user_id = auth.uid());
$$;

-- Public/student access: classes, content and tests can be read after anonymous sign-in.
create policy "students and teachers can read classes" on public.classes for select to authenticated using (true);
create policy "teachers manage classes" on public.classes for all to authenticated using (public.is_teacher()) with check (public.is_teacher());

create policy "authenticated can read vocabulary" on public.vocabulary for select to authenticated using (true);
create policy "teachers manage vocabulary" on public.vocabulary for all to authenticated using (public.is_teacher()) with check (public.is_teacher());

create policy "authenticated can read grammar" on public.grammar for select to authenticated using (true);
create policy "teachers manage grammar" on public.grammar for all to authenticated using (public.is_teacher()) with check (public.is_teacher());

create policy "authenticated can read readings" on public.readings for select to authenticated using (true);
create policy "teachers manage readings" on public.readings for all to authenticated using (public.is_teacher()) with check (public.is_teacher());

create policy "authenticated can read tests" on public.tests for select to authenticated using (true);
create policy "teachers manage tests" on public.tests for all to authenticated using (public.is_teacher()) with check (public.is_teacher());

create policy "teachers can read results" on public.results for select to authenticated using (public.is_teacher());
create policy "students can submit results" on public.results for insert to authenticated with check (not public.is_teacher());

create policy "teachers can read own teacher row" on public.teachers for select to authenticated using (user_id = auth.uid());

insert into public.classes (name, code, level) values
('B2.2','B2G101','B2'),
('B2.4','C1A202','B2')
on conflict (code) do nothing;

insert into public.vocabulary (class_id, word, meaning, example, level, pos)
select id,'take something for granted','uważać coś za oczywiste','Don''t take your health for granted.','B2','phrase' from public.classes where code='B2G101'
and not exists (select 1 from public.vocabulary v join public.classes c on c.id=v.class_id where c.code='B2G101' and v.word='take something for granted');
insert into public.vocabulary (class_id, word, meaning, example, level, pos)
select id,'meticulous','skrupulatny; bardzo dokładny','She is meticulous about her work.','B2','adjective' from public.classes where code='C1A202'
and not exists (select 1 from public.vocabulary v join public.classes c on c.id=v.class_id where c.code='C1A202' and v.word='meticulous');

insert into public.grammar (class_id,area,level,question,answer,options,explanation)
select id,'Conditionals','B2','If I ___ about the problem, I would have acted differently.','had known','["knew","have known","would know"]'::jsonb,'Third conditional: if + past perfect.' from public.classes where code='C1A202'
and not exists (select 1 from public.grammar g join public.classes c on c.id=g.class_id where c.code='C1A202' and g.question like 'If I%problem%');

insert into public.readings (class_id,title,level,date,text,items)
select id,'Free Public Transport?','B2','2026-09-16','Several cities have experimented with free public transport. Supporters argue that removing fares can encourage people to leave their cars at home. Critics point out that the policy can be costly and that additional buses may be needed when demand rises.','[["fare","opłata za przejazd","noun"],["supporter","zwolennik","noun"],["demand","popyt; zapotrzebowanie","noun"]]'::jsonb from public.classes where code='B2G101'
and not exists (select 1 from public.readings r join public.classes c on c.id=r.class_id where c.code='B2G101' and r.title='Free Public Transport?');
insert into public.readings (class_id,title,level,date,text,items)
select id,'Adaptation and Appropriation','B2','2026-09-16','An adaptation transforms a source text for a new medium, audience or purpose. Appropriation can go further by relocating material into a substantially different cultural or artistic context. Both processes invite readers to consider what is retained, changed or newly created.','[["adaptation","adaptacja","noun"],["appropriation","twórcze przejęcie / zawłaszczenie","noun"],["retained","zachowany","adjective"]]'::jsonb from public.classes where code='C1A202'
and not exists (select 1 from public.readings r join public.classes c on c.id=r.class_id where c.code='C1A202' and r.title='Adaptation and Appropriation');
